### ISSUE TITLE
r3b/phantomjs on osx

### ISSUE THREAD

**Issue by fxlacroix** [r3b/phantomjs#7]
Hi there,

I have tried this version on osx 10.8.5, the build.sh works fine, and then i get dumb:
doing 

```
bin/phantomjs --load-plugins=true
```

return me Error: Unknown option: load-plugins

I may have forget something

regards.

**Comment by r3b** [comment]
That sounds like something is missing, because those options are not very deep in the code. Let me see if I can get it to compile on Mavericks...

**Comment by r3b** [comment]
I was able to eventually get things compiling, though I had to do some hacking to make things compatible with Mavericks: https://github.com/r3b/phantomjs/tree/mavericks

Just a thought: When you went through the build process, did you compile from master or from the 1.9.0 tag? The difference is that the tags are from the releases of the core project and DO NOT contain my changes.  In order to get the plugin support, you would have to build from the master branch of my repo.

**Comment by jackfengibm** [comment]
Hi Ryan, I tried to compile from master and the mavericks branch on Mac Mavericks.  Both compilations failed with the following errors:

ld: library not found for -lQtWebKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: **\* [../bin/phantomjs] Error 1
make: **\* [sub-src-phantomjs-pro-make_default-ordered] Error 2

When compiled on the mavericks branch, I also got the following error before  I got the error message above:

../../WebCore/platform/text/mac/StringImplMac.mm:24:10: fatal error: 'FoundationExtras.h' file not found
#include "FoundationExtras.h"

By the way, I did have qt-4.8.6 installed in my system.

**Comment by JamesMGreene** [comment]
Building from the `r3b/phantomjs@mavericks` branch didn't work for me either:

```
ld: library not found for -lQtWebKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [../bin/phantomjs] Error 1
make: *** [sub-src-phantomjs-pro-make_default-ordered] Error 2
```

(But building from the `ariya/phantomjs@1.x` branch _does_ work for me.)

**Comment by r3b** [comment]
Folks, @linktohack sent in a pull request for this branch. I was able to build from there and see flash initialized.

**Comment by r3b** [comment]
For the first couple of tests, I can see that Flash is initialized, but the plugin output is not visible in the screen captures. I seem to remember reading that, due to the way Flash works on OSX, it is always rendered in a separate window instance. Does anyone know of a good fix (or cheap hack) we can use to get things rendered together?

**Comment by linktohack** [comment]
It works fine for me on OS X, we just need to install Adobe Flash (and maybe XQuartz)…
